######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/hardware-city-logo.png"
logo_on_black: "/img/hardware-city-logo.png"
custom_js: []
custom_css: ["css/session-photos.css"]

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: "https://github.com/HardwareCity/hardwarecity.github.io/blob/master"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: "" # -- to add
  flickr: ""
  github: "https://github.com/HardwareCity"
  instagram: "" # -- to add
  landscape: ""
  linkedin: "" # -- to add
  mastodon: ""
  pinterest: ""
  rss: "" # -- to add
  slack: "" # -- to add
  stackoverflow: ""
  threads: ""
  twitter: "https://twitter.com/hardwarecityhq"
  x: ""
  youtube: "" # -- to add
