blank_issues_enabled: true
contact_links:
  - name: 💬 Discord
    url: https://discord.gg/mF3na6DY # TODO @dvcorreia: this is not a permanent community link
    about: Please ask and answer questions here